### ISSUE TITLE
Brackets in the "summary" annotation aren't escaped

### ISSUE THREAD

**Issue by pierrediancourt** [idealista/prom2teams#186]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

I encountered the same kind of problem than #181 and #103 when putting brackets `[]` in the summary field.

### Steps to Reproduce

1. Create a prometheus alert like the following
```  
- alert: container-down
    expr: absent(container_start_time_seconds{group="prod", name="whoami"})      
    for: 30s  
    labels:  
      severity: fatal  
    annotations:  
      summary: |
               "[{{ $labels.location }}][{{ $labels.os }}][{{ $labels.name }}]
               Container down"
      description: "The container is down for more than 30 seconds."
```  
2. trigger it 
3. check the logs to find something like this

> prom2teams.app.exceptions.MicrosoftTeamsRequestException: Error performing request to: https://outlook.office.com/webhook/SomeGuidHere/IncomingWebhook/SomeGuidHere.
 Returned status code: 400.
 Returned data: Bad payload received by generic incoming webhook.

**Expected behavior:** the brackets `[]` being automatically escaped by prom2teams before crafting the query to send to the webhook endpoint.

**Actual behavior:** There's an already pretty clear error in the logs and the card isn't sent

**Reproduces how often:** Every time there's a json reserved character i guess

### Versions

2.5.4

### Additional Information

Jinja2 template used 
```
{%- set
  theme_colors = {
    'resolved' : '2DC72D',
    'critical' : '8C1A1A',
    'severe' : '8C1A1A',
    'warning' : 'FF9A0B',
    'unknown' : 'CCCCCC'
  }
-%}

{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "{% if status=='resolved' %} {{ theme_colors.resolved }} {% else %} {{ theme_colors[msg_text.severity] }} {% endif %}",
    "summary": "{% if status=='resolved' %}(Resolved) {% endif %}{{ msg_text.summary }}",
    "title": "Prometheus alert {% if status=='resolved' %}(Resolved) {% elif status=='unknown' %} (status unknown) {% endif %}",
    "sections": [{
        "activityTitle": "{{ msg_text.summary }}",
        "facts": [{% if msg_text.name %}{
            "name": "Alert",
            "value": "{{ msg_text.name }}"
        },{% endif %}{% if msg_text.severity %}{
            "name": "Severity",
            "value": "{{ msg_text.severity }}"
        },{% endif %}{% if msg_text.description %}{
            "name": "Description",
            "value": "{{ msg_text.description }}"
        },{% endif %}{
            "name": "Status",
            "value": "{{ msg_text.status }}"
        }{% if msg_text.extra_labels %}{% for key in msg_text.extra_labels %},{
            "name": "{{ key }}",
            "value": "{{ msg_text.extra_labels[key] }}"
        }{% endfor %}{% endif %}],
          "markdown": false
    }],
    "potentialAction": [
        {
            "@context": "http://schema.org",
            "@type": "ViewAction",
            "name": "View in grafana",
            "target": [
                "https://example.com"
            ]
        }
    ]
}

```

**Comment by pierrediancourt** [comment]
I've used https://messagecardplayground.azurewebsites.net to validate the MessageCard ouput in my error log and i think it may rather be the line return that causes the error. Not the brackets as they're enclosed in double quotes.

I'm trying to fix the problem by editing my prometheus alert.

**Comment by pierrediancourt** [comment]
Removing the double quotes as below doesn't change anything
```
- alert: container-down
    expr: absent(container_start_time_seconds{group="prod", name="whoami"})      
    for: 30s  
    labels:  
      severity: fatal  
    annotations:  
      summary: |
               [{{ $labels.location }}][{{ $labels.os }}][{{ $labels.name }}]
               Container down
      description: "The container is down for more than 30 seconds."
```
It's good to note that both code extract are valid configurations.
