### ISSUE TITLE
[FEATURE] Add possibility to configure proxy to the Deployment containers in the values.yaml file

### ISSUE THREAD

**Issue by MathiasAkerberg** [idealista/prom2teams#239]
### Description

I am not able to configure proxy properties for the containers in the corresponding Deployment resource template. At least following environment variables would be a desire to be able to set through the `values.yaml`:

- `HTTP_PROXY`
- `HTTPS_PROXY`
- `NO_PROXY`

### Why is this needed?

In some situations the network environment where the Kubernetes cluster is located requires that you configure proxy variables to be able to communicate out on the internet. This is not possible in the current Helm chart version.

**Comment by ebini** [comment]
Hi,

add  in deployment.yaml (the range to end block

```
          - name: PROM2TEAMS_GROUP_ALERTS_BY
            value: {{ .Values.prom2teams.group_alerts_by | quote }}
          {{- range $key, $value := .Values.extraEnv }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
          resources:
```


than you can set via values
```
extraEnv:
  HTTPS_PROXY: "http://proxy.url:8080"
  HTTP_PROXY: "http://proxy.url:8080"
```

perhaps i will write a pull request later...
