### ISSUE TITLE
Can this helm chart be added to any chart repo, So that we can use the same in our flux cd directly

### ISSUE THREAD

**Issue by kabilanmani93** [idealista/prom2teams#321]
### Description

Can the chart be added to any repo, so that we can use helmrelease object in flux cd

**for example: (prometheus cloudwatch exporter deployment using flux cd)**

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm search repo prometheus-community

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-cloudwatch-exporter-gitlab
  namespace: gitlab-monitoring
spec:
  releaseName: prometheus-cloudwatch-exporter-gitlab
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-cloudwatch-exporter
    version: 0.22.0
  values:

### Why is this needed?

To use it in flux cd helm releaseobject

**Comment by ebini** [comment]
Hi,

in flux you can directly add this repositry

Define the repo:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prom2teams-chart
  namespace: flux-system
spec:
  interval: 12h
  ref:
    tag: "4.2.0"
    
  url: https://github.com/idealista/prom2teams.git
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/
```

and the Helmchart reference the repo.
````
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom2teams
spec:
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: prom2teams-chart
  interval: 10m
  releaseName: oprom2teams
```

But i agree: a public "real" helm chart would be nice

Also to improve the chart. I want to add a Pull request soon.

Best regards
Ebini
